name: Pytest Automation 

# Los eventos que desencadenan el workflow son push y pull_request en la rama main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Se otorgan permisos de lectura al workflow
permissions:
  contents: read

jobs:
  # job_id:
  python-tests:
    runs-on: windows-latest

    steps:
    # Esta acción clona el repositorio en la máquina virtual
    - uses: actions/checkout@v4
    
    - name: Set up Python
    # Esta acción instala una versión específica de Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    
    - name: Install dependencies (Windows)
      run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
      shell: pwsh
    
    - name: Test with pytest
      run: |
        # Ejecutar las pruebas
        pytest
